[[redirects]]
  from = "/mcpcard"
  to = "http://43.130.247.176:5190/mcpcard"
  status = 200
  force = true

[[redirects]]
  from = "/mcpcard/:id"
  to = "http://43.130.247.176:5190/mcpcard/:id"
  status = 200
  force = true

[[redirects]]
  from = "/mcpserver/:serverName"
  to = "http://43.130.247.176:5190/mcpserver/:serverName"
  status = 200
  force = true

[[redirects]]
  from = "/mcpcard/import"
  to = "http://43.130.247.176:5190/mcpcard/import"
  status = 200
  force = true