version: '3.9'

services:
  postgres:
    image: postgres
    container_name: mcp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcpforge
    ports:
      - "5435:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mcpforge"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: